Typography 글꼴적용 입니다.
APP-iOS3rd/PJ3T5_Trackus pull request #4
Opened 2024-01-19 04:13 UTC by Teoler

타이틀 서브타이틀 본문 타이틀 본문 입니다.
`struct MyTypography {

    //타이틀
    static func title(text: String) -> Text {
        return Text(text)
            .font(Font.system(size: 28, weight: .bold))
    }
    //서브 타이틀
    static func subtitle(text: String) -> Text {
        return Text(text)
            .font(Font.system(size: 20, weight: .semibold))
    }
    //본문 타이틀
    static func bodytitle(text: String) -> Text {
        return Text(text)
            .font(Font.system(size: 17, weight: .semibold))
    }
    //본문
    static func body(text: String) -> Text {
        return Text(text)
            .font(Font.system(size: 15, weight: .regular))
            .foregroundColor(.gray)
    }
}`
사용은 다음과 같습니다
`VStack {
            //예시
            MyTypography.title(text: "트랙어스 TrackUs")
            MyTypography.subtitle(text: "트랙어스 TrackUs")
            MyTypography.bodytitle(text: "트랙어스 TrackUs")
            MyTypography.body(text: "트랙어스 TrackUs")

        }`
        
텍스트만 입력하면 자동으로 적용되도록 만들었습니다

2024-01-19 04:26 UTC, PinkSoju approved these changes
확인했습니다.

2024-01-19 04:31 UTC, Choe-ju approved these changes
확인했습니다!

2024-01-19 04:41 UTC, Choe-ju requested changes
혹시 폰트스타일만 지정할 수 있는 것도 추가 가능할까요??
Text사용하지 않는 경우에도 통일된 스타일로 변경할수있게..
TextField사용하거나 picker사용하거나 할 경우에는 별도로 지정을 해줘야 해서 커스텀 스타일로 있으면 사용하고 통합하기 좋을 것 같아요!

아 추가로 폰트 색상 변경도 필요한거 같아요!
배경이 검은색이다 보니 .white로 수정 필요합니다

2024-01-20 05:51 UTC, Choe-ju approved these changes
확인했습니다!

2024-01-20 05:51 UTC, merged